
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getTimelineWindowData(params: GetTimelineDataParams) : Promise<Result<UiWindowUsageCell[], UiAppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_window_data", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimelineAppData(params: GetTimelineDataParams) : Promise<Result<UiAppUsageCell[], UiAppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_app_data", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type GetTimelineDataParams = { start: string; end: string; duration: number; time_option: UiTimeOption }
export type UiAppError = { Other: string }
export type UiAppUsage = { app_identifier: string; duration: UiTimeDelta }
export type UiAppUsageCell = { start_time: string; data: UiAppUsageCellData | null }
export type UiAppUsageCellData = { duration: UiTimeDelta; usage: UiAppUsage[] }
export type UiTimeDelta = { secs: number; nanos: number }
export type UiTimeOption = "Hours" | "Minutes" | "Seconds" | "Days" | "Weeks"
export type UiWindowUsage = { app_identifier: string; window_name: string; duration: string }
export type UiWindowUsageCell = { start_time: string; data: UiWindowUsageCellData | null }
export type UiWindowUsageCellData = { duration: UiTimeDelta; usage: UiWindowUsage[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
